coverage:
  status:
    project:
      core:
        target: auto
        flags:
          - core
      integration:
        target: auto
        flags:
          - dynamodb
          - mariadb
          - mongodb
          - postgres
    patch:
      core:
        target: auto
        flags:
          - core
      integration:
        target: auto
        flags:
          - dynamodb
          - mariadb
          - mongodb
          - postgres

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

flags:
  core:
    carryforward: true
    paths:
      - packages/core/coverage/
  dynamodb:
    carryforward: true
    paths:
      - packages/integration/dynamodb/coverage/
  mariadb:
    carryforward: true
    paths:
      - packages/integration/mariadb/coverage/
  mongodb:
    carryforward: true
    paths:
      - packages/integration/mongodb/coverage/
  postgres:
    carryforward: true
    paths:
      - packages/integration/postgres/coverage/
