coverage:
  status:
    project:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
      core:
        target: 90%
        flags:
          - core
      integrations:
        target: 90%
        flags:
          - integrations
    patch:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error

comment:
  layout: "header, diff, flags, components, files"
  behavior: default
  require_changes: true
  require_base: true
  require_head: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: core
      paths:
        - packages/core
      carryforward: true
    - name: integrations
      paths:
        - packages/integration/dynamodb
        - packages/integration/mariadb
        - packages/integration/mongodb
        - packages/integration/postgres
      carryforward: true
