coverage:
  status:
    project:
      core:
        target: auto
        flags:
          - core
      integration:
        target: auto
        flags:
          - dynamodb
          - mariadb
          - mongodb
          - postgres
    patch:
      core:
        target: auto
        flags:
          - core
      integration:
        target: auto
        flags:
          - dynamodb
          - mariadb
          - mongodb
          - postgres

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

flag_management:
  default_rules:
    carryforward: true
  individual_flags:
    - name: core
      carryforward: true
      paths:
        - packages/core/
    - name: dynamodb
      carryforward: true
      paths:
        - packages/integration/dynamodb/
    - name: mariadb
      carryforward: true
      paths:
        - packages/integration/mariadb/
    - name: mongodb
      carryforward: true
      paths:
        - packages/integration/mongodb/
    - name: postgres
      carryforward: true
      paths:
        - packages/integration/postgres/
