-- @ocoda/event-sourcing-postgres: migration of the 3.x tables of the default pools to schema v2 (4.0).
--
-- GENERATED by `pnpm --filter @ocoda/event-sourcing-postgres gen:migration-sql`; do not edit.
--
-- These are the statements that PostgresEventStore.migrate() and PostgresSnapshotStore.migrate() run for the
-- "events" and "snapshots" tables as 3.0.1 and 3.0.2 create them. Other pools, other index names (3.0.0 used fixed
-- names) or other column types need other statements: run migrate({ dryRun: true }), which prints the exact
-- statements for your database, and use this file as a reference only.
--
-- Stop every 3.x instance and take a backup first. Run it as the owner of the tables:
--
--   psql -v legacy_time_zone='Europe/Brussels' -f migrations/4.0.sql
--
-- legacy_time_zone is the time zone your 3.x instances ran in: 3.x stored the snapshots' registered_on as the wall
-- time of the process. Each table is migrated in one transaction.

\set ON_ERROR_STOP on

-- Events: numbered in 3.x's order (event_date, event_id, stream_id, version), keeping each stream in version order.

-- create-catalog
SELECT pg_advisory_xact_lock(hashtext('ocoda:event_sourcing_collections')); CREATE TABLE IF NOT EXISTS event_sourcing_collections (
	name TEXT PRIMARY KEY,
	kind TEXT NOT NULL CHECK (kind IN ('events', 'snapshots')),
	schema_version INTEGER NOT NULL,
	last_position BIGINT NOT NULL DEFAULT 0 CHECK (last_position >= 0)
) WITH (fillfactor = 50);

-- begin
BEGIN ISOLATION LEVEL READ COMMITTED; SET LOCAL lock_timeout = '10000ms'; SET LOCAL statement_timeout = 0; SET LOCAL work_mem = '64MB'; SET LOCAL maintenance_work_mem = '256MB';

-- lock
LOCK TABLE "events" IN ACCESS EXCLUSIVE MODE;

-- number
CREATE TEMPORARY TABLE "es_migrate_862417b9e7c3" ON COMMIT DROP AS
SELECT stream_id, version, event, payload, event_id, aggregate_id, occurred_on, correlation_id, causation_id, row_number() OVER (ORDER BY stream_key, version) AS global_position
FROM (
	SELECT *, max(legacy_rank) OVER (PARTITION BY stream_id ORDER BY version ROWS UNBOUNDED PRECEDING) AS stream_key
	FROM (
		SELECT stream_id, version, event, payload, event_id, aggregate_id, occurred_on, correlation_id, causation_id,
			row_number() OVER (ORDER BY event_date, event_id, stream_id, version) AS legacy_rank
		FROM "events"
	) ranked
) keyed;

-- widen-columns
ALTER TABLE "events" ADD COLUMN IF NOT EXISTS global_position BIGINT, ADD COLUMN IF NOT EXISTS headers JSONB, ADD COLUMN IF NOT EXISTS event_version INTEGER, ALTER COLUMN stream_id TYPE TEXT, ALTER COLUMN event TYPE TEXT, ALTER COLUMN event_id TYPE TEXT, ALTER COLUMN aggregate_id TYPE TEXT, ALTER COLUMN correlation_id TYPE TEXT, ALTER COLUMN causation_id TYPE TEXT;

-- truncate
TRUNCATE "events";

-- drop-event-date
ALTER TABLE "events" ALTER COLUMN global_position SET NOT NULL, DROP COLUMN event_date;

-- reinsert
INSERT INTO "events" (stream_id, version, event, payload, event_id, aggregate_id, occurred_on, correlation_id, causation_id, global_position)
SELECT stream_id, version, event, payload, event_id, aggregate_id, occurred_on, correlation_id, causation_id, global_position FROM "es_migrate_862417b9e7c3" ORDER BY global_position;

-- index-positions
CREATE UNIQUE INDEX IF NOT EXISTS "idx_events_global_position" ON "events" (global_position);

-- register
INSERT INTO event_sourcing_collections (name, kind, schema_version, last_position)
VALUES ('events', 'events', 2, (SELECT COALESCE(MAX(global_position), 0) FROM "events"))
ON CONFLICT (name) DO UPDATE SET kind = EXCLUDED.kind, schema_version = EXCLUDED.schema_version,
	last_position = GREATEST(event_sourcing_collections.last_position, EXCLUDED.last_position)
WHERE event_sourcing_collections.kind <> EXCLUDED.kind OR event_sourcing_collections.schema_version <> EXCLUDED.schema_version
	OR event_sourcing_collections.last_position < EXCLUDED.last_position;

-- commit
COMMIT;

-- vacuum
VACUUM (ANALYZE, PARALLEL 0) "events";

-- Snapshots: one latest flag per stream, on its highest version.

-- begin
BEGIN ISOLATION LEVEL READ COMMITTED; SET LOCAL lock_timeout = '10000ms'; SET LOCAL statement_timeout = 0; SET LOCAL work_mem = '64MB'; SET LOCAL maintenance_work_mem = '256MB';

-- lock
LOCK TABLE "snapshots" IN ACCESS EXCLUSIVE MODE;

-- drop-legacy-indexes
DROP INDEX "idx_snapshots_aggregate_name_latest";

-- unflag
UPDATE "snapshots" s SET latest = NULL
WHERE s.latest IS NOT NULL AND EXISTS (SELECT 1 FROM "snapshots" n WHERE n.stream_id = s.stream_id AND n.version > s.version);

-- flag
UPDATE "snapshots" s SET latest = 'latest#' || s.stream_id
WHERE s.latest IS DISTINCT FROM 'latest#' || s.stream_id
	AND NOT EXISTS (SELECT 1 FROM "snapshots" n WHERE n.stream_id = s.stream_id AND n.version > s.version);

-- convert-columns
ALTER TABLE "snapshots" ALTER COLUMN stream_id TYPE TEXT, ALTER COLUMN snapshot_id TYPE TEXT, ALTER COLUMN aggregate_id TYPE TEXT, ALTER COLUMN aggregate_name TYPE TEXT, ALTER COLUMN latest TYPE TEXT COLLATE "C", ALTER COLUMN registered_on TYPE TIMESTAMPTZ USING registered_on AT TIME ZONE :'legacy_time_zone';

-- index-latest
CREATE UNIQUE INDEX IF NOT EXISTS "idx_snapshots_latest" ON "snapshots" (aggregate_name, latest) WHERE latest IS NOT NULL;

-- register
INSERT INTO event_sourcing_collections (name, kind, schema_version)
VALUES ('snapshots', 'snapshots', 2)
ON CONFLICT (name) DO UPDATE SET kind = EXCLUDED.kind, schema_version = EXCLUDED.schema_version
WHERE event_sourcing_collections.kind <> EXCLUDED.kind OR event_sourcing_collections.schema_version <> EXCLUDED.schema_version;

-- commit
COMMIT;

-- vacuum
VACUUM (ANALYZE, PARALLEL 0) "snapshots";
