import type { ColumnInfo, IndexInfo, TableInfo } from '../postgres.schema.js';
import type { CollectionInspection, CollectionKind } from './inspect.js';
import { type PlannedStep, planEventMigration, planSnapshotMigration } from './plan.js';

// The SQL of migrations/4.0.sql: the statements migrate() runs for the default pools of a schema that 3.0.1 or 3.0.2
// created, for DBAs who run the stores with `ddl: 'none'`. `pnpm gen:migration-sql` writes it, and
// tests/unit/postgres.migration-sql.spec.ts fails when it differs from what the planner produces.

const column = (name: string, type: string, notNull: boolean, collation: string | null = null): ColumnInfo => ({
	name,
	type,
	notNull,
	collation,
});

const index = (name: string, columns: string[], unique = false): IndexInfo => ({
	name,
	unique,
	primary: unique,
	valid: true,
	partial: false,
	plain: true,
	method: 'btree',
	columns,
});

/**
 * The tables 3.0.1 and 3.0.2 create for the default pools.
 */
const LEGACY_TABLES: Record<CollectionKind, { name: string; table: TableInfo }> = {
	events: {
		name: 'events',
		table: {
			oid: 0,
			catalog: false,
			columns: Object.fromEntries(
				[
					column('stream_id', 'character varying(120)', true, 'default'),
					column('version', 'integer', true),
					column('event', 'character varying(80)', true, 'default'),
					column('payload', 'jsonb', true),
					column('event_date', 'character varying(7)', true, 'default'),
					column('event_id', 'character varying(40)', true, 'default'),
					column('aggregate_id', 'character varying(40)', true, 'default'),
					column('occurred_on', 'timestamp with time zone', true),
					column('correlation_id', 'character varying(255)', false, 'default'),
					column('causation_id', 'character varying(255)', false, 'default'),
				].map((info) => [info.name, info]),
			),
			indexes: [
				index('events_pkey', ['stream_id', 'version'], true),
				index('idx_events_event_date_id', ['event_date', 'event_id']),
			],
		},
	},
	snapshots: {
		name: 'snapshots',
		table: {
			oid: 0,
			// The events part of the file creates it
			catalog: true,
			columns: Object.fromEntries(
				[
					column('stream_id', 'character varying(90)', true, 'default'),
					column('version', 'integer', true),
					column('payload', 'jsonb', true),
					column('snapshot_id', 'character varying(40)', true, 'default'),
					column('aggregate_id', 'character varying(40)', true, 'default'),
					column('registered_on', 'timestamp without time zone', true),
					column('aggregate_name', 'character varying(50)', true, 'default'),
					column('latest', 'character varying(100)', false, 'default'),
				].map((info) => [info.name, info]),
			),
			indexes: [
				index('snapshots_pkey', ['stream_id', 'version'], true),
				index('idx_snapshots_aggregate_name_latest', ['aggregate_name', 'latest']),
			],
		},
	},
};

const legacyInspection = (kind: CollectionKind): CollectionInspection => ({
	kind,
	...LEGACY_TABLES[kind],
	state: 'v1',
	rows: 0,
	gappedStreams: { total: 0, sample: [] },
	rewrites: [],
	triggers: [],
	publications: [],
	referencingForeignKeys: [],
	columnDependents: [],
	privileges: { owner: true, createInSchema: true, temporary: true, catalog: true },
});

/**
 * The steps a DBA runs: without the session lock, which only keeps two migrate() runs apart.
 */
const statementsOf = (steps: PlannedStep[]): string =>
	steps.map(({ name, statement }) => `-- ${name}\n${statement};`).join('\n\n');

/**
 * The steps of a table's migration, run only while the table still has the 3.x shape (`guard`), so that the file can
 * run again after a failure or a partial run.
 */
const guarded = (
	table: string,
	guard: string,
	steps: PlannedStep[],
): string => `SELECT ${guard} AS migrate_${table} \\gset
\\if :migrate_${table}

${statementsOf(steps.filter(({ name }) => name !== 'migration-lock' && name !== 'create-catalog'))}

\\else
\\echo '${table}: no 3.x table to migrate, skipped'
\\endif`;

/**
 * The content of migrations/4.0.sql.
 */
export const renderMigrationSql = (): string => {
	const settings = { lockTimeoutMs: 10_000, legacyTimeZone: 'UTC', timeZoneSql: ":'legacy_time_zone'" };
	const events = planEventMigration(legacyInspection('events'), settings);
	const snapshots = planSnapshotMigration(legacyInspection('snapshots'), settings);

	return `-- @ocoda/event-sourcing-postgres: migration of the 3.x tables of the default pools to schema v2 (4.0).
--
-- GENERATED by \`pnpm --filter @ocoda/event-sourcing-postgres gen:migration-sql\`; do not edit.
--
-- These are the statements that PostgresEventStore.migrate() and PostgresSnapshotStore.migrate() run for the
-- "events" and "snapshots" tables as 3.0.1 and 3.0.2 create them. Other pools, other index names (3.0.0 used fixed
-- names) or other column types need other statements: run migrate({ dryRun: true }), which prints the exact
-- statements for your database, and use this file as a reference only.
--
-- Stop every 3.x instance and take a backup first. Run it with psql (10 or later), as the owner of the tables:
--
--   psql -v legacy_time_zone='Europe/Brussels' -f migrations/4.0.sql
--
-- legacy_time_zone is the time zone your 3.x instances ran in: 3.x stored the snapshots' registered_on as the wall
-- time of the process. Each table is migrated in one transaction, and only while it still has its 3.x shape, so the
-- file can run again after a failure.

\\set ON_ERROR_STOP on

\\if :{?legacy_time_zone}
\\else
\\echo 'Set legacy_time_zone to the time zone your 3.x instances ran in: psql -v legacy_time_zone=<IANA zone> -f migrations/4.0.sql'
\\quit
\\endif

-- The catalog of the collections, unless it exists.

${statementsOf(events.steps.filter(({ name }) => name === 'create-catalog'))}

-- Events: numbered in 3.x's order (event_date, event_id, stream_id, version), keeping each stream in version order.

${guarded('events', "EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = to_regclass('events') AND attname = 'event_date' AND NOT attisdropped)", events.steps)}

-- Snapshots: one latest flag per stream, on its highest version.

${guarded('snapshots', "EXISTS (SELECT 1 FROM pg_attribute WHERE attrelid = to_regclass('snapshots') AND attname = 'registered_on' AND atttypid = 'timestamp'::regtype AND NOT attisdropped)", snapshots.steps)}
`;
};
