import { EventCollection, SnapshotCollection } from '@ocoda/event-sourcing';
import { backupTableName } from '../mariadb.schema.js';
import { type MigrationPlan, type PlanOptions, planEventMigration, planSnapshotMigration } from './plan.js';
import { DEFAULT_STATEMENT_OPTIONS, dropBackupSql } from './sql.js';

/**
 * `migrations/4.0.sql`: the statements that `MariaDBEventStore.migrate()` and `MariaDBSnapshotStore.migrate()` run for
 * the default pools' tables as 3.x creates them, rendered from the planner with the default options. The package
 * script `gen:migration-sql` writes it, and a spec fails when it drifts from the planner.
 */

const HEADER = `-- @ocoda/event-sourcing-mariadb: migration of the 3.x tables of the default pools to schema v2 (4.0).
--
-- GENERATED by \`pnpm --filter @ocoda/event-sourcing-mariadb gen:migration-sql\`; do not edit.
--
-- These are the statements that MariaDBEventStore.migrate() and MariaDBSnapshotStore.migrate() run for the \`events\`
-- and \`snapshots\` tables as 3.x creates them, with the default options (keepBackup, repairOccurredOn, a 10 s lock
-- wait). Other pools, a server with NO_BACKSLASH_ESCAPES, or tables that were changed by hand need other statements:
-- run migrate({ dryRun: true }), which reports the exact statements for your database, and use this file as a
-- reference only.
--
-- Stop every 3.x instance and take a backup first. Run it in the database of the tables, as a user that may create,
-- alter and rename them:
--
--   mariadb --database=<database> < migrations/4.0.sql
--
-- The acquire-lock statements fail with error 1242 (Subquery returns more than 1 row) when another migration of the
-- table holds its lock, which stops the client there.
`;

const renderPlan = (title: string, plan: MigrationPlan): string =>
	[`-- ${title}`, ...plan.steps.map(({ name, statement, lock }) => `\n-- ${name} (lock: ${lock})\n${statement};`)].join(
		'\n',
	);

/** The options of the rendered statements: the defaults of `migrate()`. */
export const RENDER_OPTIONS: PlanOptions = { ...DEFAULT_STATEMENT_OPTIONS, keepBackup: true, repairOccurredOn: true };

export const renderMigrationSql = (): string => {
	const events = EventCollection.get();
	const snapshots = SnapshotCollection.get();
	const eventPlan = planEventMigration(
		{ table: events, state: 'v1', registered: false, hasColumns: true, backup: false, dependents: [] },
		RENDER_OPTIONS,
	);
	const snapshotPlan = planSnapshotMigration(
		{
			table: snapshots,
			state: 'v1',
			registered: false,
			hasColumns: true,
			columnsConverted: false,
			latestIndexes: ['idx_aggregate_name_latest'],
			uniqueLatest: false,
			dependents: [],
			// The event migration above keeps the 3.x events as its backup: the snapshot streams take their events' ids
			events: backupTableName(events),
		},
		RENDER_OPTIONS,
	);
	return `${[
		HEADER,
		renderPlan(
			'Events: copied into a schema v2 table, numbered in 3.x order (event_date, event_id, stream_id, version) with every stream in version order, and swapped in. The rows of a 3.x stream whose ids differ in case only take the stream id of its lowest version. 3.x inserts fail from the swap on (1136).',
			eventPlan,
		),
		renderPlan(
			"Snapshots: every stream takes the stream id of its events (of its lowest snapshot, without events), then the table is converted in place (binary collation, DATETIME(3) in UTC), with one latest flag per stream, on its highest version. The events' backup must still exist.",
			snapshotPlan,
		),
		`\n-- Once satisfied with the migrated events and snapshots, drop the 3.x table that the swap kept:\n-- ${dropBackupSql(events)};`,
	].join('\n\n')}\n`;
};
