import { EVENT_LISTENER_METADATA as EmitterMetadata } from '@nestjs/event-emitter/dist/constants';

export const AGGREGATE_METADATA = 'AGGREGATE_METADATA';
export const COMMAND_HANDLER_METADATA = 'COMMAND_HANDLER_METADATA';
export const COMMAND_METADATA = 'COMMAND_METADATA';
export const EVENT_LISTENER_METADATA = EmitterMetadata;
export const EVENT_METADATA = 'EVENT_METADATA';
export const EVENT_SERIALIZER_METADATA = 'EVENT_SERIALIZER_METADATA';
export const QUERY_HANDLER_METADATA = 'QUERY_HANDLER_METADATA';
export const QUERY_METADATA = 'QUERY_METADATA';
export const SNAPSHOT_METADATA = 'SNAPSHOT_METADATA';
