name: CD Docs

on:
  workflow_dispatch:
  push:
    branches: ["master"]
    paths:
      - docs/**

permissions: {}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
    steps:
      - name: Checkout the repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup job environment
        uses: ./.github/actions/setup-job-env
        with:
          node-version: 24.x

      - name: Build
        run: pnpm docs:build --filter=@ocoda/event-sourcing-docs
        env:
          GITHUB_PAGES: true

      - name: Upload build
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./docs/dist

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Publish to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
